### ISSUE TITLE
Features and bugs

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#36]
Good day to you!

My machine:

OS: NixOS 22.05
CPU: Xeon 2650L v3
RAM: 32 GB
GPU: HD7570

compiled not with `legacyrenderer`

Some features and bugs during testing:
* feat: opacity (transparency) option without blurring
* bug: xkb option not working
* bug: blurring not working
* bug: right-click menu not working in brave (but working in firefox)
* feat: how to `expo` like in `wayfire` or `overview` like in `newm`?
* feat: how to `scale` like in `wayfire`?
* feat: ability to set relative size and move in `rules` (for example , to align window to center< bottom, top, right, corners etc.)
* feat: ability to split config
* feat: touchpad settings

<details>
<summary>my hyprland config</summary>

```conf  
# ---------------------------
#           startup
# ---------------------------

exec-once=wezterm start
exec-once = wl-paste --watch cliphist store
exec-once = wlsunset -l 54.73 -L 55.95
exec-once = dunst

exec=ei util wallpaper

# ---------------------------
#           general
# ---------------------------

autogenerated=0 # remove this line to get rid of the warning on top.
# monitor=,1920x1080@60,0x0,0.5,1
monitor=,1024x768@60,0x0,1,1

input {
    xkb_layout = us,ru
    xkb_model =
    xkb_options = grp:win_space_toggle
    xkb_rules = evdev
    follow_mouse = 1
}

general {
    max_fps=100
    sensitivity=0.9
    main_mod=SUPER

    gaps_in=5
    gaps_out=15
    border_size=2
    col.active_border=0x66222222
    col.inactive_border=0x66333333
}

decoration {
    rounding=18
    blur=0
    blur_size=3
    blur_passes=1
}

animations {
    enabled=1
    windows=1
    borders=1
    fadein=1 # fade in AND out
    speed=7
    # windows_speed=3 # specific speeds for components can be made with name_speed=float. 0 means use global (speed=float). If not set, will use the global value.
    # borders_speed=1
    # fadein_speed=7
}

dwindle {
    pseudotile=1 # enable pseudotiling on dwindle
}

# -------------------------
#           rules
# -------------------------
# example window rules
# for windows named/classed as abc and xyz
windowrule=move 1 1,util
windowrule=size 300 300,util
# windowrule=tile,xyz
windowrule=float,util
windowrule=pseudo,util
# windowrule=monitor 0,xyz#


# ------------------------
#           keys
# ------------------------

# basic binds
bind=SUPER,return,exec,wezterm start --class 'terminal' --always-new-process
bind=SUPERSHIFT,return,exec,wezterm start --class "util" ei launch
bind=SUPER,end,exec,wezterm start --class "util" ei util power
bind=SUPER,print,exec,grim -g "$(slurp)" - | swappy -f -
bind=SUPER,home,exec,wezterm start --class "util" ei

bind=SUPER,delete,killactive,
# bind=SUPERSHIFT,delete,exec,pkill Hyprland
bind=SUPER,F,togglefloating,
bind=SUPER,t,pseudo,
bind=SUPERSHIFT,F,fullscreen,

bind=SUPER,H,movefocus,l
bind=SUPER,J,movefocus,d
bind=SUPER,K,movefocus,u
bind=SUPER,L,movefocus,l

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9

bind=SUPERSHIFT,1,movetoworkspace,1
bind=SUPERSHIFT,2,movetoworkspace,2
bind=SUPERSHIFT,3,movetoworkspace,3
bind=SUPERSHIFT,4,movetoworkspace,4
bind=SUPERSHIFT,5,movetoworkspace,5
bind=SUPERSHIFT,6,movetoworkspace,6
bind=SUPERSHIFT,7,movetoworkspace,7
bind=SUPERSHIFT,8,movetoworkspace,8
bind=SUPERSHIFT,9,movetoworkspace,9

```
 </details>

**Comment by FlyingStitchman** [comment]
Opacity should be disabled with `blur=0`, so if windows are still blurred with your setup, that is a bug. 
Alternatively, could you expand on what is not working about the blurring, or is there literally no blur? 

Right-click menu in Brave is working for me, I will edit after trying with `psuedotile=1` to see if that is potentially causing it.

I also would find the overview feature a nice addition. With that, would it also be possible to create statically assigned workspaces that are more than the default. I use multiple monitors, and it would be nice to have workspaces 7-0 for my side monitor and 1-4 for my main one for example, instead of making sure to switch to the monitor I want to open a new workspace in before opening a workspace.

In addition to touchpad settings, could you also add a way to lock absolute positional devices (like drawing tablets) to monitors (similar to wayfire). Bonus points to allow horizontal and vertical scaling for non-standard aspect ratios. I have not tested yet as I forgot my pen and have yet to retrieve it, but since there is no mention in the config, and that there are no touchpad settings, I imagine it has not had development.

I am using Arch and Nvidia.

**Comment by fedoranvar** [comment]
@FlyingStitchman  
about opacity: 
blurring is not working at all, but i'm noticing that when it's on, whole system is slowing down
and i was suggesting to enable opacity without blurring, right now i can't see an option for that

in addtition to touchpad settings:
that would be great if it was possible to rotate touchpad

**Comment by FlyingStitchman** [comment]
@fedoranvar 
Disabling blurring enables opacity by default, or at least that is how it works on my system.

The slowdown is likely due to the performance cost of the blurring, especially because you are using an old/not super powerful GPU, although it always could be due to the bug that is not showing blurring on your computer. Although, now that I think about it, I may have noticed some slowdowns on rocket league due to blurring.... Anyways, I think the blurring is going to be reworked significantly due to @vaxerski mentioning replacing the shader in this issue #31 .

Another thing about the blur, it might be blurring all active windows instead of just transparent windows, which could lead to some of the issues we talked about, although I am not sure on that. It would be interesting to disable blur for specific windows (think whitelist or blacklist).

**Comment by vaxerski** [comment]
opacity without blurring: so like picom's active-opacity and inactive-opacity?

xkb option not working: example of an option? I don't use those and cant test.

blurring not working: it works, but with your GPU it might just be so slow and costly it dies.

right-click menu not working in brave: what? it does for me. Maybe try using brave in wayland, and not XWayland mode. (idk how to force that though)

expo, overview: is it like seeing all the workspaces at once? not implemented yet, and I doubt it will be soon.

scale, you mean scale an output? technically possible with the monitor= config

split config: so like `source`? doable.

touchpads: thats far in the bucket list, I have way more important stuff to fix and implement, touchpads will be supported but I need time.

May I remind you this project is 4 weeks old, and I have finals in 2.5 weeks. The progress will ramp back up at the end of May, but still this is a huge project and features might take time.

Nevertheless, if you feel adventurous, you can try implementing some yourself and making a PR.

cheers.

**Comment by vaxerski** [comment]
> In addition to touchpad settings, could you also add a way to lock absolute positional devices

no, unless someone lends me a drawing tablet, no idea how wlroots responds to those.

> Another thing about the blur, it might be blurring all active windows instead of just transparent windows

it does, I should alpha test.

**Comment by vaxerski** [comment]
> blurring is not working at all, but i'm noticing that when it's on, whole system is slowing down
and i was suggesting to enable opacity without blurring, right now i can't see an option for that

opacity is on by default. All apps that write to their buffers with non-opaque pixels will have non-opaque pixels.

Maybe XWayland is fucking sonething up for ya?

**Comment by fedoranvar** [comment]
@vaxerski 

First of all, thank you for your time and effort to it,  i didn't meant to hurry or push.  
I want to help and contribute as possible to this project.

question: is there any planning for `plugin` system, similar to `wayfire`'s?

**Comment by vaxerski** [comment]
>  is there any planning for plugin system, siaybemilar to wayfire's?

probably not.

> xkb switching still not working.

no idea, I've got 0 experience with this.

> expo and overview of workspaces (like, grid or ,maybe, inline)

can do, but such eyecandy is far back in the bucket list

> scale is a plugin in wayfire - it's like expo but for windows in current workspace-monitor

same as above

> opacity, yeah, like in picom. ability to set opacity in range from 0.0 to 1.0, of active or inactive, maybe handling it in rules?

will be

> ability to set bluring for transparent windows (like in wayfire or picom)
(kawase, gaussian, box etc.) in wayfire it's not so resource-hogging.

first of all, I don't use either of the three, so probably, yes. Second, try turning on damage tracking (recommended on `monitor` as `full` is still pretty buggy). It is resource-hogging, just that damage tracking makes everything less performance-hogging.

**Comment by fedoranvar** [comment]
got it . thank you!

**Comment by fedoranvar** [comment]
about `expo` (`overview`):
there is some  `sway` implementation, maybe it could help

 https://github.com/milgra/sov

**Comment by ldy3112** [comment]
> > In addition to touchpad settings, could you also add a way to lock absolute positional devices
> 
> no, unless someone lends me a drawing tablet, no idea how wlroots responds to those.

About the drawing tablet, it didn't respond to pressure (at least mine won't. It's a Veikk S640), but I can move the cursor. Can confirm this is not wayland's because it works on Sway and GNOME. I'll gladly help (e.g. logs or something) if somebody can integrate these. Gonna learn about wlroots and also try implementing it myself lmao.

**Comment by AlistairKeiller** [comment]
I can second that pen pressure is not working ( I have a One by Wacom ). It was working at some point, any only broke in a more recent release of hyprland.

**Comment by ldy3112** [comment]
You're using OpenTabletDriver like mentioned in Hyprland's wiki right?

**Comment by AlistairKeiller** [comment]
I was not using OTD because I wanted pen pressure not just clicking with the pen. The wacom driver should, and did, provide pen pressure info. The issue is that I switched my chromium based browser to Auto Ozone platform which broke its ability to read the pen pressure.
